import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync,cpSync,existsSync,readFileSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {spawnSync} from 'node:child_process';
import {TOOL_ROOT,downloadsDirectory,externalPath,loadSettings,initSettings} from '../lib/settings.mjs';
import {writeJson} from '../lib/shared.mjs';
import {compileGenerate} from '../lib/generate.mjs';
import {analyzeStyle} from '../lib/analyze.mjs';
import {executePlan,checkRun} from '../lib/executor.mjs';
function fixture(fn){const root=mkdtempSync(join(tmpdir(),'art-workshop-settings-'));try{return fn(root);}finally{rmSync(root,{recursive:true,force:true});}}
test('Windows 实际下载目录及环境变量解析',()=>{assert.equal(downloadsDirectory({platform:'win32',home:'fallback',env:{USERPROFILE:'D:/用户'},knownFolder:()=>'%USERPROFILE%/下载'}),'D:/用户/下载');});
test('Linux XDG 自定义下载目录与macOS默认目录',()=>fixture(root=>{const config=join(root,'xdg');mkdirSync(config);writeFileSync(join(config,'user-dirs.dirs'),'XDG_DOWNLOAD_DIR="$HOME/Custom Downloads"');assert.equal(downloadsDirectory({platform:'linux',home:root,env:{XDG_CONFIG_HOME:config}}),join(root,'Custom Downloads'));assert.equal(downloadsDirectory({platform:'darwin',home:root,env:{}}),join(root,'Downloads'));}));
test('本地配置创建、保持已有内容和命令行路径覆盖',()=>fixture(root=>{const file=join(root,'config.json');initSettings(file);const config={paths:{workspace:join(root,'data'),output:join(root,'images'),refs:join(root,'refs'),cache:join(root,'cache')},execution:{model:'custom-model',size:'512*512',perValue:2,promptExtend:false,watermark:false},defaultProject:'cellgame',analysisModel:'visual-model',autoSyncSkills:false};writeJson(file,config);initSettings(file);assert.deepEqual(JSON.parse(readFileSync(file,'utf8')),config);const effective=loadSettings({file,refs:join(root,'custom-refs')});assert.equal(effective.paths.refs,join(root,'custom-refs'));assert.equal(effective.paths.output,config.paths.output);assert.equal(effective.execution.perValue,2);}));
test('运行资源不能写到安装目录，非法设置提前拒绝',()=>fixture(root=>{assert.throws(()=>externalPath(join(TOOL_ROOT,'image.png')),/之外/);const file=join(root,'config.json');writeJson(file,{paths:{workspace:TOOL_ROOT}});assert.throws(()=>loadSettings({file}),/之外/);writeJson(file,{execution:{size:'1K'}});assert.throws(()=>loadSettings({file}),/像素/);writeJson(file,{unknown:true});assert.throws(()=>loadSettings({file}),/字段/);}));
test('指定参考目录参与预演，缓存和报告保持外部',()=>fixture(root=>{cpSync(join(TOOL_ROOT,'tests/fixtures/projects'),join(root,'projects'),{recursive:true});const refs=join(root,'reference files');mkdirSync(refs);writeFileSync(join(refs,'source.png'),'reference');const result=analyzeStyle({projectId:'cellgame',root,refsDir:refs,cacheDir:join(root,'cache'),input:{project:'cellgame',id:'ref-test',description:'简洁风格',constraints:[],refs:[{path:'source.png',scope:'style',note:'观察视觉语言'}]},dry:true});assert.equal(result.requests[0][3],join(refs,'source.png'));assert.equal(existsSync(join(root,'cache')),false);}));
test('预演与真实执行路由到同一个自定义输出根，原图验收有效',()=>fixture(root=>{cpSync(join(TOOL_ROOT,'tests/fixtures/projects'),join(root,'projects'),{recursive:true});const plan=compileGenerate({projectId:'cellgame',jobId:'skills',root,localExecution:{model:'custom-model'}});assert.equal(plan.execution.model,'custom-model');const item=plan.items[0],output=join(root,'download','image.g');const dry=executePlan(plan,[item],{outputRoot:output,dry:true,log:()=>{}});assert.equal(dry.requests[0].args[dry.requests[0].args.indexOf('--out-dir')+1],join(output,'<runId>'));assert.equal(existsSync(output),false);const run=executePlan(plan,[item],{outputRoot:output,log:()=>{},runner:args=>{writeFileSync(join(args[args.indexOf('--out-dir')+1],'image.png'),'generated');return {};}});assert.ok(run.runDir.startsWith(output));assert.equal(checkRun(run.manifest,run.manifestPath)[0].integrity,true);}));
test('CLI使用一份配置选择外部工程、模型和输出，预演不写工具目录',()=>fixture(root=>{const workspace=join(root,'workspace');cpSync(join(TOOL_ROOT,'tests/fixtures/projects'),join(workspace,'projects'),{recursive:true});const file=join(root,'config.json'),output=join(root,'images');writeJson(file,{paths:{workspace,output,refs:join(root,'refs'),cache:join(root,'cache')},execution:{model:'local-model'},defaultProject:'cellgame',autoSyncSkills:false});const run=spawnSync(process.execPath,[join(TOOL_ROOT,'art-workshop.mjs'),'generate','run','--config',file,'--job','skills','--item','skill-01','--dry'],{encoding:'utf8'});assert.equal(run.status,0,run.stderr);const args=JSON.parse(run.stdout).requests[0].args;assert.equal(args[args.indexOf('--model')+1],'local-model');assert.equal(args[args.indexOf('--out-dir')+1],join(output,'<runId>'));assert.equal(existsSync(output),false);}));
